# CONFIG
spring.application.name=Kuroneko
server.port=${PORT:80}
spring.banner.location=classpath:Banner/banner.txt

# DATABASE
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/kuroneko}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update

# KEYS
kuroneko.tokens.youtube=${YOUTUBE_TOKEN:}
kuroneko.tokens.discord=${DISCORD_TOKEN:}
kuroneko.tokens.riot=${RIOT_TOKEN:}

# IDs
kuroneko.id.owner=${OWNER_ID:0}
kuroneko.id.olek=${OLEK_ID:0}
kuroneko.id.ponyskiller=${PONYSKILLER_ID:0}